import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Image from "next/image";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Firecom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${spaceGrotesk.className} w-screen h-screen bg-white flex justify-center items-center`}
      >
        <div className='container w-[405px] h-[845px] scale-[0.73] border overflow-hidden'>
          {children}
        </div>
      </body>
    </html>
  );
}
